version: '3.8'

services:

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"  # web interface
      - "7687:7687"  # database connections
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/import
      - neo4j_plugins:/plugins

  graph-generation:
    build:
      context: ./
      dockerfile: ./generation/Dockerfile
    stdin_open: true
    volumes:
      - ./:/usr/app/
    container_name: graph-generation

  graph-matching:
    build:
      context: ./
      dockerfile: ./matching/Dockerfile
    stdin_open: true
    volumes:
      - ./:/usr/app/
    container_name: graph-matching

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins: