from enum import Enum

NODE_PREFIX = "node_"

NO_DESIGN_PATTERN = "N/A"


class NodeAttr( Enum ):
    LABELS = NODE_PREFIX + "labels"
    SCOPED_RECORD_NAME = NODE_PREFIX + "scopedRecordName"
    DATASET = NODE_PREFIX + "dataset"
    FULL_NAME = NODE_PREFIX + "fullName"
    LOCAL_NAME = NODE_PREFIX + "localName"
    PATTERN_ID_NAME = NODE_PREFIX + "patternId"


class EdgeAttr( Enum ):
    TYPE = "type"


class EdgeType( Enum ):
    INTERACTS = "INTERACTS"


class NodeLabel( Enum ):
    RECORD = "RecordDeclaration"
    KNOWS_RECORD = "KNOWS_RECORD"
    CREATES_RECORD = "CREATES_RECORD"
    EXTENDED_BY_RECORD = "EXTENDED_BY_RECORD"
    RETURNS_RECORD = "RETURNS_RECORD"
    CALLS_RECORD = "CALLS_RECORD"


DEFAULT_INTERACTION_IDX = 1


class DesignPatternType( Enum ):
    ABSTRACT_FACTORY = "ABSTRACT_FACTORY"
    ADAPTER = "ADAPTER"
    BUILDER = "BUILDER"
    FACADE = "FACADE"
    FACTORY_METHOD = "FACTORY_METHOD"
    OBSERVER = "OBSERVER"
    SINGLETON = "SINGLETON"
    DECORATOR = "DECORATOR"
    MEMENTO = "MEMENTO"
    PROTOTYPE = "PROTOTYPE"
    PROXY = "PROXY"
    VISITOR = "VISITOR"

    """
    # ADDITIONAL
    COMMAND = "COMMAND"
    COMPOSITE = "COMPOSITE"
    STATE = "STATE"
    ITERATOR = "ITERATOR"
    NULL_OBJECT = "NULL_OBJECT"
    TEMPLATE_METHOD = "TEMPLATE_METHOD"
    BRIDGE = "BRIDGE"
    STRATEGY = "STRATEGY"
    """
